#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FS_AddVolAndroid.Resource", IsApplication=true)]

namespace FS_AddVolAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int directory_item_height = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int horizontal_page_margin = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int margin_huge = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int margin_large = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int margin_medium = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int margin_small = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int margin_tiny = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int vertical_page_margin = 2130968586;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_description_grey600_36dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_folder_grey600_36dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tile = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int button_create_directory = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int button_open_directory = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int container = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int divisor = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int entry_image = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int label_current_directory = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int recyclerview_directory_entries = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int textview_current_directory = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int textview_filename = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int textview_mimetype = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_directory_selection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int directory_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_directory_selection = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int cancel = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int create_directory = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int intro_message = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int ok = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int open_directory = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int selected_directory = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070003
			public const int AppTheme = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int DirectoryEntryNameFont = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Base = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Sample = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int Widget = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Widget_SampleMessage = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Widget_SampleMessageTile = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
